version: '3.8'

# To build these containers use `docker-compose build`
# To run the containers use `docker-compose up -d`
# To bring down the containers use `docker-compose down -v`

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: web-${REACT_APP_ENV}
    container_name: web_${REACT_APP_ENV}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    env_file:
      - .env
    volumes:
      # Mount our filesystem into the running container
      - .:/usr/src/app
      # Specify the node_modules directory as a volume so that the host's copy does not overwrite
      # what is in the docker image. See: https://stackoverflow.com/a/32785014
      - /usr/src/app/node_modules